### ISSUE TITLE
Model enhancements

### ISSUE THREAD

**Issue by kimobrian** [AndelaOSP/wire-api#62]
### Features and Tasks

- [x] Have an eslint file for the project.
- [x] Update the update incident endpoint.
  - [x] If an incident is updated to include an assignee, add the assignee to the incident.
      - [x] When a incident gets an assignee, ensure to set their `assigneeRole`, (assignee, ccd or other).
      **Example**
```js
// Example
const User = sequelize.define('user', {})
const Project = sequelize.define('project', {})
const UserProjects = sequelize.define('userProjects', {
    status: DataTypes.STRING
})

User.belongsToMany(Project, { through: UserProjects })
Project.belongsToMany(User, { through: UserProjects })
/*
To add a new project to a user and set its status, you pass extra options.through to the setter, which contains the attributes for the join table
*/

user.addProject(project, { through: { status: 'started' }})
// incident.addWitness(witness, {through: { assignedRole: /*role*/}})
```
- [x] Update the user and incident models to factor in witnesses. Retrieving an incident should also include witnesses. Retrieving a user should include a list of incidents they are witnesses to(Id's only).
- [x] Update `services/locations.js` to use use `findOrCreate` instead of the manual checking. Same for when a new user submits an incident. Scrap it off if its not very important. Means updating `incident->create`.

*Personal opinion: Remove services folder and let everything happen under controllers*
- Sync with @bmuthoga to ensure everything is fine when saving incidents and users.
